### ISSUE TITLE
Question about latent supervision.

### ISSUE THREAD

**Issue by synsin0** [BraveGroup/LAW#1]
Thanks for your amazing work! I'd like to ask about latent supervision. I think it is similar to PETR approach with a set of queries cross attention with 3D PE + image features. Then these queries are quantized and cross attention to decode waypoints only. Do you use pretrained PETR model or use intermediate supervision? Only using waypoint as supervision is similar to BEV-planner approach with a sparse paradigm. I'm really curious about it. Thanks again.

**Comment by liyingyanUCAS** [comment]
Our latent supervision is not related to PETR. We only utilize PETR's 3D PE  to enhance the image feature, without using a pretrained PETR model or intermediate supervision. The latent supervision comes from the latent world model and waypoints.

**Comment by synsin0** [comment]
Thanks for your answers. Look forward to your code!
